import os
import csv
import datetime
import subprocess

def extract_course(username):
    course_mappings = {
        "dic": "dic",
        "vlsi_lab": "vlsi_lab",
        "dcic": "dcic",
        "aiclab": "aiclab",
        "aicintro": "aicintro",
        "iclab": "iclab",
        "asoc": "asoc",
        "soc": "soc",
        "vlsilab": "vlsilab",
        "VLSI": "VLSI",
        "pmic": "pmic",
        "mcs": "mcs",
        "mlchip": "mlchip",
        "DCS": "DCS",
        "aicintro": "aicintro",
        "dcs": "dcs",
        "aic": "aic",
        "semi_aic": "semi_aic",
        "icst_dic": "icst_dic",
        "vlsi" : "vlsi"
        
    }
    Manager = {
        "Si2man" : "Si2man",
        "lhlaib" : "lhlaib",
        "sctech" : "sctech"
    }
    for keyword, course in course_mappings.items():
        if keyword in username:
            if "RA" in username:
                return "RA", course
            elif "TA" in username:
                return "TA", course
            else:
                return "Stu", course
    if username in Manager:
        return "Manager", "Manager"
    if "RA" in username:
        return "", "RA"
    return "", "others"

# Set the current date and time
current_datetime = datetime.datetime.now().strftime("%Y-%m-%d--%H-%M-%S")
csv_filename = f"data/{current_datetime}.csv"

# Read server info from the AllHosts file
servers = []
with open("AllHosts", "r") as hosts_file:
    for line in hosts_file:
        hostname, ssh_port = line.strip().split(":")
        servers.append({"hostname": hostname, "ssh_port": ssh_port})


# Command to get user and login info using pssh
pssh_command = "pssh -h AllHosts -l root -o ./output who"

# Execute pssh command to collect data
try:
    subprocess.check_output(pssh_command, shell=True)
except subprocess.CalledProcessError:
    print("Failed to execute pssh command")

# Process output files generated by pssh
data = []
for server in servers:
    output_filename = f"./output/{server['hostname']}:{server['ssh_port']}"
    try:
        with open(output_filename, "r") as output_file:
            for line in output_file:
                parts = line.split()
                # print(parts)
                if len(parts) >= 4:
                    username = parts[0]
                    login_ip = parts[4][1:-1] # Remove parentheses
                    role,course = extract_course(username)
                    data.append((server['hostname'], server['ssh_port'], role,course, username, login_ip))
    except FileNotFoundError:
        print(f"Output file not found for {server['hostname']}")

# Save data to a CSV file
with open(csv_filename, "w", newline="") as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(["Hostname", "SSH Port", "Role", "Course/Lab", "Username", "Login IP"])
    csv_writer.writerows(data)

# print(data)
# print(f"Data saved to {csv_filename}")

